url: http://hannarenee.github.io
baseurl:

# Site settings
title: Youmewe Media
email: hallo@youmewemedIa.nl
description: "Youmewe Media, website diensten voor onderneemsters. Website maken. Website onderhouden. WordPress hulp. Hoger in Google komen: SEO."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Cyrille Montulet
  pic: 1
  position: freelance filmmaakster
  quote: Hanna wist mijn ideeÃ«n die ik voor ogen had uitstekend te vertalen naar een perfect werkende site. Met haar up-to-date expertise op gebied van Wordpress heeft Hanna mij vele tips meegegeven en met een heldere uitleg geleerd hoe ik zelf mijn eigen site kan onderhouden. Kortom, de naam 'You-Me-We Media omvat exact waar het om draait, Je eigen idee + Hanna haar deskundigheid = samen kom je tot een geweldig resultaat. en aanrader!

- name: Leonie Hosselet
  pic: 2
  position: freelance journaliste
  quote: Ik heb Hanna gevraagd een website voor mij als freelance journalist te ontwerpen. Ondanks dat we zussen zijn, heeft Hanna een goede balans gevonden tussen informaliteit en professionaliteit. Wat me opviel waren haar enthousiasme en toewijding. Hanna is een autodidact die continue zoekt naar nieuwe kennis, die verwerft en meteen toepast.

- name: Zobaida El Khanchouf
  pic: 3
  position: eigenaresse Al Haya'shop
  quote: Geweldig!

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/youmewemedia
  - title: facebook
    url: http://facebook.com/youmewemedia
  - title: google-plus
    url: http://plus.google.com/+YouMeWeMediaAlmere
  - title: linkedin
    url: http://linkedin.com/in/hannahosselet
  - title: github
    url: http://github.com/hannarenee

# Postal address (add as many lines as necessary)
address:
  - line: Doetinchempad 9
  - line: 1324 JW Almere

# Build settings
markdown: kramdown
permalink: pretty
